In [1]:
import os
import sys
from pathlib import Path
from scipy.signal import argrelextrema

import pandas as pd
import numpy as np

from bu_candles import buCandles, bu_prints
from be_candles import beCandles, be_prints
from moving_averages import movingAverages
from studies import regStudies
from drawings import makeDrawings

import importlib
importlib.reload(sys.modules['bu_candles'])
importlib.reload(sys.modules['be_candles'])
importlib.reload(sys.modules['moving_averages'])
importlib.reload(sys.modules['studies'])

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', None)

In [2]:
# Get current working directory and go one level up
base_dir = f"{Path(os.getcwd()).parents[0]}/data/"
fname = 'AAPL_2021-01-04_daily'
df_aapl = pd.read_pickle(os.path.join(base_dir, fname))

In [3]:
df_aapl = movingAverages.return_df(movingAverages(df_aapl))
df_aapl = regStudies.return_df(regStudies(df_aapl))

In [4]:
bu_prints(df_aapl)

Bullish Marubuzo
##################################################
17      2016-01-29
35      2016-02-25
149     2016-08-08
246     2016-12-23
269     2017-01-30
287     2017-02-24
355     2017-06-02
465     2017-11-08
1030    2020-02-10
Name: date, dtype: object

Bullish Doji
##################################################
52      2016-03-21
195     2016-10-12
237     2016-12-12
281     2017-02-15
313     2017-04-03
335     2017-05-04
347     2017-05-22
505     2018-01-08
646     2018-07-31
697     2018-10-11
896     2019-07-30
946     2019-10-09
1240    2020-12-08
Name: date, dtype: object

Bullish Spinning Top
##################################################
55      2016-03-24
76      2016-04-25
101     2016-05-31
104     2016-06-03
143     2016-07-29
162     2016-08-25
191     2016-10-06
201     2016-10-20
320     2017-04-12
327     2017-04-24
335     2017-05-04
350     2017-05-25
376     2017-07-05
456     2017-10-26
545     2018-03-07
568     2018-04-10
574     2018-04-18
607     2018-06-05
617     2018-06-19
618     2018-06-20
628     2018-07-05
708     2018-10-26
793     2019-03-04
854     2019-05-30
896     2019-07-30
901     2019-08-06
952     2019-10-17
1039    2020-02-24
1120    2020-06-18
1168    2020-08-26
1177    2020-09-09
1202    2020-10-14
1221    2020-11-10
1250    2020-12-22
Name: date, dtype: object

Bullish Dragonfly Doji
##################################################
46      2016-03-11
200     2016-10-19
296     2017-03-09
354     2017-06-01
749     2018-12-27
1160    2020-08-14
1190    2020-09-28
1243    2020-12-11
Name: date, dtype: object

Bullish Inverted Hammer
##################################################
129     2016-07-11
227     2016-11-28
239     2016-12-14
567     2018-04-09
720     2018-11-13
1049    2020-03-09
1087    2020-05-01
Name: date, dtype: object

Bullish Hammer
##################################################
46      2016-03-11
1160    2020-08-14
Name: date, dtype: object

Bullish Kicker
##################################################
500     2017-12-29
1031    2020-02-11
1147    2020-07-28
Name: date, dtype: object

Bullish Engulfing
##################################################
237     2016-12-12
1110    2020-06-04
Name: date, dtype: object

Bullish Harami
##################################################
145     2016-08-02
1045    2020-03-03
1124    2020-06-24
Name: date, dtype: object

Bullish Piercing Line
##################################################
Series([], Name: date, dtype: object)

Bullish Tweezer Bottom
##################################################
13    2016-01-25
Name: date, dtype: object

Bullish Morning Star
##################################################
30      2016-02-18
89      2016-05-12
651     2018-08-07
796     2019-03-07
1024    2020-01-31
1144    2020-07-23
Name: date, dtype: object

Bullish Abandoned Baby
##################################################
Series([], Name: date, dtype: object)

Bullish 3 White Soldiers
##################################################
148    2016-08-05
463    2017-11-06
529    2018-02-12
Name: date, dtype: object

Bullish 3 Line Strike
##################################################
138    2016-07-22
Name: date, dtype: object

Bullish Morning Star Doji
##################################################
960     2019-10-29
1214    2020-10-30
Name: date, dtype: object

Bullish 3 Outside Up
##################################################
125    2016-07-05
581    2018-04-27
Name: date, dtype: object

Bullish 3 Inside Up
##################################################
218    2016-11-14
397    2017-08-03
627    2018-07-03
714    2018-11-05
Name: date, dtype: object

In [5]:
be_prints(df_aapl)

Bearish Spinning Top
##################################################
26      2016-02-11
65      2016-04-08
133     2016-07-15
177     2016-09-16
195     2016-10-12
208     2016-10-31
224     2016-11-22
281     2017-02-15
289     2017-02-28
312     2017-03-31
333     2017-05-02
342     2017-05-15
369     2017-06-22
408     2017-08-18
471     2017-11-16
476     2017-11-24
490     2017-12-14
513     2018-01-19
560     2018-03-28
571     2018-04-13
597     2018-05-21
604     2018-05-31
643     2018-07-26
795     2019-03-06
862     2019-06-11
886     2019-07-16
904     2019-08-09
934     2019-09-23
937     2019-09-26
1010    2020-01-10
1022    2020-01-29
1139    2020-07-16
1215    2020-11-02
1247    2020-12-17
Name: date, dtype: object

Bearish Dragonfly Doji
##################################################
66      2016-04-11
587     2018-05-07
788     2019-02-25
905     2019-08-12
1054    2020-03-16
Name: date, dtype: object

Bearish Hanging Man
##################################################
296    2017-03-09
425    2017-09-13
813    2019-04-01
Name: date, dtype: object

Bearish Shooting Star
##################################################
905    2019-08-12
Name: date, dtype: object

Bearish Grave Stone
##################################################
Series([], Name: date, dtype: object)

Bearish Kicker
##################################################
Series([], Name: date, dtype: object)

Bearish Engulfing
##################################################
Series([], Name: date, dtype: object)

Bearish Harami
##################################################
1154    2020-08-06
Name: date, dtype: object

Bearish Dark Cloud Cover
##################################################
290     2017-03-01
366     2017-06-19
590     2018-05-10
659     2018-08-17
675     2018-09-11
730     2018-11-28
803     2019-03-18
1044    2020-03-02
1102    2020-05-22
1141    2020-07-20
1200    2020-10-12
1253    2020-12-28
Name: date, dtype: object

Bearish Tweezer Top
##################################################
487     2017-12-11
525     2018-02-06
700     2018-10-16
1154    2020-08-06
Name: date, dtype: object

Bearish Abandoned Baby
##################################################
Series([], Name: date, dtype: object)

Bearish 3 Black Crows
##################################################
70      2016-04-15
744     2018-12-19
1254    2020-12-29
1255    2020-12-30
Name: date, dtype: object

Bearish Evening Doji Star
##################################################
23     2016-02-08
828    2019-04-23
873    2019-06-26
Name: date, dtype: object

Bearish Evening Star
##################################################
Series([], Name: date, dtype: object)

In [6]:
df_aapl = makeDrawings.return_df(makeDrawings(df_aapl))

In [7]:
df_aapl.head(10)

,close,high,low,open,symbol,volume,id,key,subkey,date,updated,changeOverTime,marketChangeOverTime,uOpen,uClose,uHigh,uLow,uVolume,fOpen,fClose,fHigh,fLow,fVolume,label,change,...,cd_bupline,cd_butbot,cd_bumorn,cd_buababy,cd_butws,cd_butls,cd_bumsd,cd_butou,cd_butiu,cd_best,cd_bedd,cd_behm,cd_besstar,cd_begstone,cd_bekick,cd_begulf,cd_beharam,cd_bedcc,cd_bettop,cd_beababy,cd_betbc,cd_beeds,cd_bees,localMin,localMax
0,25.6775,26.4625,25.6025,26.4375,AAPL,223163968,HISTORICAL_PRICES,AAPL,,2016-01-05,1606830572000,0.000000,0.000000,105.75,102.71,105.85,102.4100,55790992,24.4936,23.7895,24.5167,23.7200,223163968,"Jan 5, 16",NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,23.7895
1,25.1750,25.5925,24.9675,25.1400,AAPL,273829552,HISTORICAL_PRICES,AAPL,,2016-01-06,1606830572000,-0.019570,-0.019570,100.56,100.70,102.37,99.8700,68457388,23.2915,23.3239,23.7107,23.1317,273829552,"Jan 6, 16",-0.4656,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,24.1125,25.0325,24.1075,24.6700,AAPL,324377712,HISTORICAL_PRICES,AAPL,,2016-01-07,1606830572000,-0.060948,-0.060948,98.68,96.45,100.13,96.4300,81094428,22.8560,22.3395,23.1919,22.3349,324377712,"Jan 7, 16",-0.9844,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.3395,NaN
3,24.2400,24.7775,24.1900,24.6375,AAPL,283192064,HISTORICAL_PRICES,AAPL,,2016-01-08,1606830572000,-0.055983,-0.055983,98.55,96.96,99.11,96.7600,70798016,22.8259,22.4577,22.9556,22.4113,283192064,"Jan 8, 16",0.1182,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,24.6325,24.7650,24.3350,24.7425,AAPL,198957508,HISTORICAL_PRICES,AAPL,,2016-01-11,1606830572000,-0.040697,-0.040697,98.97,98.53,99.06,97.3400,49739377,22.9232,22.8213,22.9441,22.5457,198957508,"Jan 11, 16",0.3636,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
5,24.9900,25.1725,24.7100,25.1375,AAPL,196616908,HISTORICAL_PRICES,AAPL,,2016-01-12,1606830572000,-0.026774,-0.026774,100.55,99.96,100.69,98.8399,49154227,23.2892,23.1525,23.3216,22.8931,196616908,"Jan 12, 16",0.3312,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
6,24.3475,25.2975,24.3250,25.0800,AAPL,249758524,HISTORICAL_PRICES,AAPL,,2016-01-13,1606830572000,-0.051796,-0.051796,100.32,97.39,101.19,97.3000,62439631,23.2359,22.5573,23.4374,22.5364,249758524,"Jan 13, 16",-0.5952,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
7,24.8800,25.1200,23.9350,24.4900,AAPL,252680508,HISTORICAL_PRICES,AAPL,,2016-01-14,1606830572000,-0.031058,-0.031058,97.96,99.52,100.48,95.7400,63170127,22.6893,23.0506,23.2730,22.1751,252680508,"Jan 14, 16",0.4933,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
8,24.2825,24.4275,23.8400,24.0500,AAPL,319335564,HISTORICAL_PRICES,AAPL,,2016-01-15,1606830572000,-0.054328,-0.054328,96.20,97.13,97.71,95.3600,79833891,22.2816,22.4970,22.6314,22.0871,319335564,"Jan 15, 16",-0.5536,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
9,24.1650,24.6625,23.8750,24.6025,AAPL,212350988,HISTORICAL_PRICES,AAPL,,2016-01-19,1606830572000,-0.058904,-0.058904,98.41,96.66,98.65,95.5000,53087747,22.7935,22.3882,22.8491,22.1195,212350988,"Jan 19, 16",-0.1088,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN

In [ ]:
?argrelextrema