In [13]:
import os
import sys
from pathlib import Path
from scipy.signal import argrelextrema

import pandas as pd
import numpy as np

from bu_candles import buCandles, bu_prints
from be_candles import beCandles, be_prints
from moving_averages import movingAverages
from studies import regStudies

import importlib
importlib.reload(sys.modules['bu_candles'])
importlib.reload(sys.modules['be_candles'])
importlib.reload(sys.modules['moving_averages'])
importlib.reload(sys.modules['studies'])

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', None)

In [9]:
# Get current working directory and go one level up
base_dir = f"{Path(os.getcwd()).parents[0]}/data/"
fname = 'AAPL_2021-01-04_daily'
df_aapl = pd.read_pickle(os.path.join(base_dir, fname))

In [10]:
df_aapl = movingAverages.return_df(movingAverages(df_aapl))
df_aapl = regStudies.return_df(regStudies(df_aapl))

In [11]:
bu_prints(df_aapl)

Bullish Marubuzo
##################################################
17      2016-01-29
35      2016-02-25
149     2016-08-08
246     2016-12-23
269     2017-01-30
287     2017-02-24
355     2017-06-02
465     2017-11-08
1030    2020-02-10
Name: date, dtype: object

Bullish Doji
##################################################
52      2016-03-21
195     2016-10-12
237     2016-12-12
281     2017-02-15
313     2017-04-03
335     2017-05-04
347     2017-05-22
505     2018-01-08
646     2018-07-31
697     2018-10-11
896     2019-07-30
946     2019-10-09
1240    2020-12-08
Name: date, dtype: object

Bullish Spinning Top
##################################################
55      2016-03-24
76      2016-04-25
101     2016-05-31
104     2016-06-03
143     2016-07-29
162     2016-08-25
191     2016-10-06
201     2016-10-20
320     2017-04-12
327     2017-04-24
335     2017-05-04
350     2017-05-25
376     2017-07-05
456     2017-10-26
545     2018-03-07
568     2018-04-10
574     2018-04-18
607     2018-06-05
617     2018-06-19
618     2018-06-20
628     2018-07-05
708     2018-10-26
793     2019-03-04
854     2019-05-30
896     2019-07-30
901     2019-08-06
952     2019-10-17
1039    2020-02-24
1120    2020-06-18
1168    2020-08-26
1177    2020-09-09
1202    2020-10-14
1221    2020-11-10
1250    2020-12-22
Name: date, dtype: object

Bullish Dragonfly Doji
##################################################
46      2016-03-11
200     2016-10-19
296     2017-03-09
354     2017-06-01
749     2018-12-27
1160    2020-08-14
1190    2020-09-28
1243    2020-12-11
Name: date, dtype: object

Bullish Inverted Hammer
##################################################
129     2016-07-11
227     2016-11-28
239     2016-12-14
567     2018-04-09
720     2018-11-13
1049    2020-03-09
1087    2020-05-01
Name: date, dtype: object

Bullish Hammer
##################################################
46      2016-03-11
1160    2020-08-14
Name: date, dtype: object

Bullish Kicker
##################################################
500     2017-12-29
1031    2020-02-11
1147    2020-07-28
Name: date, dtype: object

Bullish Engulfing
##################################################
237     2016-12-12
1110    2020-06-04
Name: date, dtype: object

Bullish Harami
##################################################
145     2016-08-02
1045    2020-03-03
1124    2020-06-24
Name: date, dtype: object

Bullish Piercing Line
##################################################
Series([], Name: date, dtype: object)

Bullish Tweezer Bottom
##################################################
13    2016-01-25
Name: date, dtype: object

Bullish Morning Star
##################################################
30      2016-02-18
89      2016-05-12
651     2018-08-07
796     2019-03-07
1024    2020-01-31
1144    2020-07-23
Name: date, dtype: object

Bullish Abandoned Baby
##################################################
Series([], Name: date, dtype: object)

Bullish 3 White Soldiers
##################################################
148    2016-08-05
463    2017-11-06
529    2018-02-12
Name: date, dtype: object

Bullish 3 Line Strike
##################################################
138    2016-07-22
Name: date, dtype: object

Bullish Morning Star Doji
##################################################
960     2019-10-29
1214    2020-10-30
Name: date, dtype: object

Bullish 3 Outside Up
##################################################
125    2016-07-05
581    2018-04-27
Name: date, dtype: object

Bullish 3 Inside Up
##################################################
218    2016-11-14
397    2017-08-03
627    2018-07-03
714    2018-11-05
Name: date, dtype: object

In [12]:
be_prints(df_aapl)

Bearish Spinning Top
##################################################
26      2016-02-11
65      2016-04-08
133     2016-07-15
177     2016-09-16
195     2016-10-12
208     2016-10-31
224     2016-11-22
281     2017-02-15
289     2017-02-28
312     2017-03-31
333     2017-05-02
342     2017-05-15
369     2017-06-22
408     2017-08-18
471     2017-11-16
476     2017-11-24
490     2017-12-14
513     2018-01-19
560     2018-03-28
571     2018-04-13
597     2018-05-21
604     2018-05-31
643     2018-07-26
795     2019-03-06
862     2019-06-11
886     2019-07-16
904     2019-08-09
934     2019-09-23
937     2019-09-26
1010    2020-01-10
1022    2020-01-29
1139    2020-07-16
1215    2020-11-02
1247    2020-12-17
Name: date, dtype: object

Bearish Dragonfly Doji
##################################################
66      2016-04-11
587     2018-05-07
788     2019-02-25
905     2019-08-12
1054    2020-03-16
Name: date, dtype: object

Bearish Hanging Man
##################################################
296    2017-03-09
425    2017-09-13
813    2019-04-01
Name: date, dtype: object

Bearish Shooting Star
##################################################
905    2019-08-12
Name: date, dtype: object

Bearish Grave Stone
##################################################
Series([], Name: date, dtype: object)

Bearish Kicker
##################################################
Series([], Name: date, dtype: object)

Bearish Engulfing
##################################################
Series([], Name: date, dtype: object)

Bearish Harami
##################################################
1154    2020-08-06
Name: date, dtype: object

Bearish Dark Cloud Cover
##################################################
290     2017-03-01
366     2017-06-19
590     2018-05-10
659     2018-08-17
675     2018-09-11
730     2018-11-28
803     2019-03-18
1044    2020-03-02
1102    2020-05-22
1141    2020-07-20
1200    2020-10-12
1253    2020-12-28
Name: date, dtype: object

Bearish Tweezer Top
##################################################
487     2017-12-11
525     2018-02-06
700     2018-10-16
1154    2020-08-06
Name: date, dtype: object

Bearish Abandoned Baby
##################################################
Series([], Name: date, dtype: object)

Bearish 3 Black Crows
##################################################
70      2016-04-15
744     2018-12-19
1254    2020-12-29
1255    2020-12-30
Name: date, dtype: object

Bearish Evening Doji Star
##################################################
23     2016-02-08
828    2019-04-23
873    2019-06-26
Name: date, dtype: object

Bearish Evening Star
##################################################
Series([], Name: date, dtype: object)

In [23]:
df_aapl = localMaxMin.return_df(localMaxMin(df_aapl))

In [24]:
df_aapl.head(100)

,close,high,low,open,symbol,volume,id,key,subkey,date,updated,changeOverTime,marketChangeOverTime,uOpen,uClose,uHigh,uLow,uVolume,fOpen,fClose,fHigh,fLow,fVolume,label,change,...,cd_bupline,cd_butbot,cd_bumorn,cd_buababy,cd_butws,cd_butls,cd_bumsd,cd_butou,cd_butiu,cd_best,cd_bedd,cd_behm,cd_besstar,cd_begstone,cd_bekick,cd_begulf,cd_beharam,cd_bedcc,cd_bettop,cd_beababy,cd_betbc,cd_beeds,cd_bees,localMin,localMax
0,25.6775,26.4625,25.6025,26.4375,AAPL,223163968,HISTORICAL_PRICES,AAPL,,2016-01-05,1606830572000,0.000000,0.000000,105.750,102.71,105.8500,102.4100,55790992,24.4936,23.7895,24.5167,23.7200,223163968,"Jan 5, 16",NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,23.7895
1,25.1750,25.5925,24.9675,25.1400,AAPL,273829552,HISTORICAL_PRICES,AAPL,,2016-01-06,1606830572000,-0.019570,-0.019570,100.560,100.70,102.3700,99.8700,68457388,23.2915,23.3239,23.7107,23.1317,273829552,"Jan 6, 16",-0.4656,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,24.1125,25.0325,24.1075,24.6700,AAPL,324377712,HISTORICAL_PRICES,AAPL,,2016-01-07,1606830572000,-0.060948,-0.060948,98.680,96.45,100.1300,96.4300,81094428,22.8560,22.3395,23.1919,22.3349,324377712,"Jan 7, 16",-0.9844,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24.1125,NaN
3,24.2400,24.7775,24.1900,24.6375,AAPL,283192064,HISTORICAL_PRICES,AAPL,,2016-01-08,1606830572000,-0.055983,-0.055983,98.550,96.96,99.1100,96.7600,70798016,22.8259,22.4577,22.9556,22.4113,283192064,"Jan 8, 16",0.1182,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,24.6325,24.7650,24.3350,24.7425,AAPL,198957508,HISTORICAL_PRICES,AAPL,,2016-01-11,1606830572000,-0.040697,-0.040697,98.970,98.53,99.0600,97.3400,49739377,22.9232,22.8213,22.9441,22.5457,198957508,"Jan 11, 16",0.3636,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
5,24.9900,25.1725,24.7100,25.1375,AAPL,196616908,HISTORICAL_PRICES,AAPL,,2016-01-12,1606830572000,-0.026774,-0.026774,100.550,99.96,100.6900,98.8399,49154227,23.2892,23.1525,23.3216,22.8931,196616908,"Jan 12, 16",0.3312,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
6,24.3475,25.2975,24.3250,25.0800,AAPL,249758524,HISTORICAL_PRICES,AAPL,,2016-01-13,1606830572000,-0.051796,-0.051796,100.320,97.39,101.1900,97.3000,62439631,23.2359,22.5573,23.4374,22.5364,249758524,"Jan 13, 16",-0.5952,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
7,24.8800,25.1200,23.9350,24.4900,AAPL,252680508,HISTORICAL_PRICES,AAPL,,2016-01-14,1606830572000,-0.031058,-0.031058,97.960,99.52,100.4800,95.7400,63170127,22.6893,23.0506,23.2730,22.1751,252680508,"Jan 14, 16",0.4933,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
8,24.2825,24.4275,23.8400,24.0500,AAPL,319335564,HISTORICAL_PRICES,AAPL,,2016-01-15,1606830572000,-0.054328,-0.054328,96.200,97.13,97.7100,95.3600,79833891,22.2816,22.4970,22.6314,22.0871,319335564,"Jan 15, 16",-0.5536,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
9,24.1650,24.6625,23.8750,24.6025,AAPL,212350988,HISTORICAL_PRICES,AAPL,,2016-01-19,1606830572000,-0.058904,-0.058904,98.410,96.66,98.6500,95.5000,53087747,22.7935,22.3882,22.8491,22.1195,212350988,"Jan 19, 16",-0.1088,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
10,24.1975,24.5474,23.3550,23.7750,AAPL,289337664,HISTORICAL_PRICES,AAPL,,2016-01-20,1606830572000,-0.057638,-0.057638,95.100,96.79,98.1897,93.4200,72334416,22.0269,22.4183,22.7425,21.6377,289337664,"Jan 20, 16",0.0301,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
11,24.0750,24.4700,23.7350,24.2650,AAPL,208645852,HISTORICAL_PRICES,AAPL,,2016-01-21,1606830572000,-0.062409,-0.062409,97.060,96.30,97.8800,94.9400,52161463,22.4808,22.3048,22.6708,21.9898,208645852,"Jan 21, 16",-0.1135,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
12,25.3550,25.3650,24.5925,24.6575,AAPL,263201868,HISTORICAL_PRICES,AAPL,,2016-01-22,1606830572000,-0.012560,-0.012560,98.630,101.42,101.4600,98.3700,65800467,22.8445,23.4907,23.4999,22.7842,263201868,"Jan 22, 16",1.1859,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,23.4907
13,24.8600,25.3825,24.8025,25.3800,AAPL,207178100,HISTORICAL_PRICES,AAPL,,2016-01-25,1606830572000,-0.031837,-0.031837,101.520,99.44,101.5300,99.2100,51794525,23.5138,23.0321,23.5162,22.9788,207178100,"Jan 25, 16",-0.4586,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
14,24.9975,25.2200,24.5175,24.9825,AAPL,300308008,HISTORICAL_PRICES,AAPL,,2016-01-26,1606830572000,-0.026482,-0.026482,99.930,99.99,100.8800,98.0700,75077002,23.1456,23.1595,23.3656,22.7148,300308008,"Jan 26, 16",0.1274,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
15,23.3550,24.1572,23.3350,24.0100,AAPL,533478696,HISTORICAL_PRICES,AAPL,,2016-01-27,1606830572000,-0.090449,-0.090449,96.040,93.42,96.6289,93.3400,133369674,22.2446,21.6377,22.3810,21.6192,533478696,"Jan 27, 16",-1.5218,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23.355,NaN
16,23.5225,23.6300,23.0975,23.4475,AAPL,222715300,HISTORICAL_PRICES,AAPL,,2016-01-28,1606830572000,-0.083926,-0.083926,93.790,94.09,94.5200,92.3900,55678825,21.7234,21.7929,21.8925,21.3992,222715300,"Jan 28, 16",0.1552,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
17,24.3350,24.3350,23.5875,23.6975,AAPL,257666016,HISTORICAL_PRICES,AAPL,,2016-01-29,1606830572000,-0.052283,-0.052283,94.790,97.34,97.3400,94.3500,64416504,21.9551,22.5457,22.5457,21.8531,257666016,"Jan 29, 16",0.7528,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
18,24.1075,24.1775,23.8500,24.1175,AAPL,163774164,HISTORICAL_PRICES,AAPL,,2016-02-01,1606830572000,-0.061143,-0.061143,96.470,96.43,96.7100,95.4000,40943541,22.3442,22.3349,22.3998,22.0963,163774164,"Feb 1, 16",-0.2108,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
19,23.6200,24.0100,23.5700,23.8550,AAPL,149428860,HISTORICAL_PRICES,AAPL,,2016-02-02,1606830572000,-0.080129,-0.080129,95.420,94.48,96.0400,94.2800,37357215,22.1010,21.8833,22.2446,21.8369,149428860,"Feb 2, 16",-0.4516,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
20,24.0875,24.2100,23.5200,23.7500,AAPL,183857176,HISTORICAL_PRICES,AAPL,,2016-02-03,1606830572000,-0.061922,-0.061922,95.000,96.35,96.8400,94.0800,45964294,22.0037,22.3164,22.4299,21.7906,183857176,"Feb 3, 16",0.4331,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
21,24.1500,24.3325,23.7975,23.9650,AAPL,185886608,HISTORICAL_PRICES,AAPL,,2016-02-04,1606830572000,-0.059488,-0.059488,95.860,96.60,97.3300,95.1900,46471652,22.3234,22.4957,22.6657,22.1673,185886608,"Feb 4, 16",0.1793,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
22,23.5050,24.2300,23.4225,24.1300,AAPL,185672256,HISTORICAL_PRICES,AAPL,,2016-02-05,1606830572000,-0.084607,-0.084607,96.520,94.02,96.9200,93.6900,46418064,22.4771,21.8949,22.5702,21.8180,185672256,"Feb 5, 16",-0.6008,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
23,23.7525,23.9250,23.2600,23.2825,AAPL,216085500,HISTORICAL_PRICES,AAPL,,2016-02-08,1606830572000,-0.074968,-0.074968,93.130,95.01,95.7000,93.0400,54021375,21.6876,22.1254,22.2861,21.6667,216085500,"Feb 8, 16",0.2305,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,NaN,NaN
24,23.7475,23.9850,23.4825,23.5725,AAPL,177324780,HISTORICAL_PRICES,AAPL,,2016-02-09,1606830572000,-0.075163,-0.075163,94.290,94.99,95.9400,93.9300,44331195,21.9578,22.1208,22.3420,21.8739,177324780,"Feb 9, 16",-0.0046,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
25,23.5675,24.0875,23.5250,23.9800,AAPL,169374404,HISTORICAL_PRICES,AAPL,,2016-02-10,1606830572000,-0.082173,-0.082173,95.920,94.27,96.3500,94.1000,42343601,22.3373,21.9531,22.4375,21.9135,169374404,"Feb 10, 16",-0.1677,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
26,23.4250,23.6800,23.1475,23.4475,AAPL,200298844,HISTORICAL_PRICES,AAPL,,2016-02-11,1606830572000,-0.087723,-0.087723,93.790,93.70,94.7200,92.5900,50074711,21.8413,21.8204,22.0579,21.5619,200298844,"Feb 11, 16",-0.1327,...,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,23.425,NaN
27,23.4975,23.6250,23.2525,23.5475,AAPL,161405524,HISTORICAL_PRICES,AAPL,,2016-02-12,1606830572000,-0.084899,-0.084899,94.190,93.99,94.5000,93.0100,40351381,21.9345,21.8879,22.0067,21.6597,161405524,"Feb 12, 16",0.0675,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
28,24.1600,24.2125,23.6525,23.7550,AAPL,196231664,HISTORICAL_PRICES,AAPL,,2016-02-16,1606830572000,-0.059098,-0.059098,95.020,96.64,96.8500,94.6100,49057916,22.1278,22.5050,22.5539,22.0323,196231664,"Feb 16, 16",0.6171,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
29,24.5300,24.5525,24.0375,24.1675,AAPL,179452972,HISTORICAL_PRICES,AAPL,,2016-02-17,1606830572000,-0.044689,-0.044689,96.670,98.12,98.2100,96.1500,44863243,22.5120,22.8497,22.8706,22.3909,179452972,"Feb 17, 16",0.3447,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,22.8497
30,24.0650,24.7225,24.0228,24.7100,AAPL,156083932,HISTORICAL_PRICES,AAPL,,2016-02-18,1606830572000,-0.062798,-0.062798,98.840,96.26,98.8900,96.0910,39020983,23.0173,22.4165,23.0290,22.3772,156083932,"Feb 18, 16",-0.4332,...,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
31,24.0100,24.1900,23.9500,24.0000,AAPL,141496692,HISTORICAL_PRICES,AAPL,,2016-02-19,1606830572000,-0.064940,-0.064940,96.000,96.04,96.7599,95.8000,35374173,22.3560,22.3653,22.5329,22.3094,141496692,"Feb 19, 16",-0.0512,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
32,24.2200,24.2250,23.9800,24.0775,AAPL,137123032,HISTORICAL_PRICES,AAPL,,2016-02-22,1606830572000,-0.056762,-0.056762,96.310,96.88,96.9000,95.9200,34280758,22.4282,22.5609,22.5656,22.3373,137123032,"Feb 22, 16",0.1956,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
33,23.6725,24.1250,23.6375,24.1000,AAPL,127770532,HISTORICAL_PRICES,AAPL,,2016-02-23,1606830572000,-0.078084,-0.078084,96.400,94.69,96.5000,94.5500,31942633,22.4491,22.0509,22.4724,22.0183,127770532,"Feb 23, 16",-0.5100,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23.6725,NaN
34,24.0250,24.0950,23.3300,23.4950,AAPL,145022980,HISTORICAL_PRICES,AAPL,,2016-02-24,1606830572000,-0.064356,-0.064356,93.980,96.10,96.3800,93.3200,36255745,21.8856,22.3793,22.4445,21.7319,145022980,"Feb 24, 16",0.3284,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
35,24.1900,24.1900,23.8125,24.0125,AAPL,110330636,HISTORICAL_PRICES,AAPL,,2016-02-25,1606830572000,-0.057930,-0.057930,96.050,96.76,96.7600,95.2500,27582659,22.3676,22.5330,22.5330,22.1813,110330636,"Feb 25, 16",0.1537,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
36,24.2275,24.5059,24.1450,24.3000,AAPL,115964524,HISTORICAL_PRICES,AAPL,,2016-02-26,1606830572000,-0.056470,-0.056470,97.200,96.91,98.0237,96.5800,28991131,22.6354,22.5679,22.8272,22.4910,115964524,"Feb 26, 16",0.0349,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
37,24.1725,24.5575,24.1625,24.2150,AAPL,140865108,HISTORICAL_PRICES,AAPL,,2016-02-29,1606830572000,-0.058612,-0.058612,96.860,96.69,98.2300,96.6500,35216277,22.5562,22.5167,22.8753,22.5073,140865108,"Feb 29, 16",-0.0512,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
38,25.1325,25.1925,24.3550,24.4125,AAPL,201628588,HISTORICAL_PRICES,AAPL,,2016-03-01,1606830572000,-0.021225,-0.021225,97.650,100.53,100.7700,97.4200,50407147,22.7402,23.4109,23.4668,22.6866,201628588,"Mar 1, 16",0.8942,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
39,25.1875,25.2225,24.9100,25.1275,AAPL,132678240,HISTORICAL_PRICES,AAPL,,2016-03-02,1606830572000,-0.019083,-0.019083,100.510,100.75,100.8900,99.6400,33169560,23.4062,23.4621,23.4947,23.2036,132678240,"Mar 2, 16",0.0512,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
40,25.3750,25.4275,25.1125,25.1450,AAPL,147822968,HISTORICAL_PRICES,AAPL,,2016-03-03,1606830572000,-0.011781,-0.011781,100.580,101.50,101.7099,100.4500,36955742,23.4225,23.6368,23.6857,23.3923,147822968,"Mar 3, 16",0.1747,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
41,25.7525,25.9375,25.3425,25.5925,AAPL,184220400,HISTORICAL_PRICES,AAPL,,2016-03-04,1606830572000,0.002921,0.002921,102.370,103.01,103.7500,101.3700,46055100,23.8394,23.9884,24.1607,23.6065,184220400,"Mar 4, 16",0.3516,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,23.9884
42,25.4675,25.7075,25.2400,25.5975,AAPL,143663240,HISTORICAL_PRICES,AAPL,,2016-03-07,1606830572000,-0.008178,-0.008178,102.390,101.87,102.8300,100.9600,35915810,23.8440,23.7229,23.9465,23.5110,143663240,"Mar 7, 16",-0.2655,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
43,25.2575,25.4400,25.1000,25.1950,AAPL,126247556,HISTORICAL_PRICES,AAPL,,2016-03-08,1606830572000,-0.016357,-0.016357,100.780,101.03,101.7600,100.4000,31561889,23.4691,23.5273,23.6973,23.3806,126247556,"Mar 8, 16",-0.1956,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
44,25.2800,25.3950,25.0675,25.3275,AAPL,108806732,HISTORICAL_PRICES,AAPL,,2016-03-09,1606830572000,-0.015480,-0.015480,101.310,101.12,101.5800,100.2700,27201683,23.5925,23.5483,23.6554,23.3503,108806732,"Mar 9, 16",0.0210,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
45,25.2925,25.5600,25.0375,25.3525,AAPL,134054308,HISTORICAL_PRICES,AAPL,,2016-03-10,1606830572000,-0.014994,-0.014994,101.410,101.17,102.2400,100.1500,33513577,23.6158,23.5599,23.8091,23.3224,134054308,"Mar 10, 16",0.0116,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
46,25.5650,25.5700,25.3750,25.5600,AAPL,109632948,HISTORICAL_PRICES,AAPL,,2016-03-11,1606830572000,-0.004381,-0.004381,102.240,102.26,102.2800,101.5000,27408237,23.8091,23.8138,23.8184,23.6368,109632948,"Mar 11, 16",0.2539,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
47,25.6300,25.7275,25.4450,25.4775,AAPL,100304248,HISTORICAL_PRICES,AAPL,,2016-03-14,1606830572000,-0.001850,-0.001850,101.910,102.52,102.9100,101.7800,25076062,23.7323,23.8743,23.9651,23.7020,100304248,"Mar 14, 16",0.0605,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
48,26.1450,26.2950,25.9625,25.9900,AAPL,160270936,HISTORICAL_PRICES,AAPL,,2016-03-15,1606830572000,0.018207,0.018207,103.960,104.58,105.1800,103.8500,40067734,24.2097,24.3540,24.4938,24.1840,160270936,"Mar 15, 16",0.4797,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
49,26.4925,26.5775,26.1475,26.1525,AAPL,153213972,HISTORICAL_PRICES,AAPL,,2016-03-16,1606830572000,0.031740,0.031740,104.610,105.97,106.3100,104.5900,38303493,24.3610,24.6777,24.7569,24.3564,153213972,"Mar 16, 16",0.3237,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
50,26.4500,26.6175,26.2400,26.3800,AAPL,137682820,HISTORICAL_PRICES,AAPL,,2016-03-17,1606830572000,0.030085,0.030085,105.520,105.80,106.4700,104.9600,34420705,24.5729,24.6381,24.7942,24.4425,137682820,"Mar 17, 16",-0.0396,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
51,26.4800,26.6250,26.2975,26.5850,AAPL,176820684,HISTORICAL_PRICES,AAPL,,2016-03-18,1606830572000,0.031253,0.031253,106.340,105.92,106.5000,105.1900,44205171,24.7639,24.6661,24.8012,24.4961,176820684,"Mar 18, 16",0.0280,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
52,26.4775,26.9125,26.2850,26.4825,AAPL,142010712,HISTORICAL_PRICES,AAPL,,2016-03-21,1606830572000,0.031156,0.031156,105.930,105.91,107.6500,105.1401,35502678,24.6684,24.6638,25.0690,24.4845,142010712,"Mar 21, 16",-0.0023,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
53,26.6800,26.8225,26.3025,26.3125,AAPL,129777500,HISTORICAL_PRICES,AAPL,,2016-03-22,1606830572000,0.039042,0.039042,105.250,106.72,107.2900,105.2100,32444375,24.5101,24.8524,24.9851,24.5007,129777500,"Mar 22, 16",0.1886,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
54,26.5325,26.7675,26.4750,26.6200,AAPL,102813980,HISTORICAL_PRICES,AAPL,,2016-03-23,1606830572000,0.033298,0.033298,106.480,106.13,107.0700,105.9000,25703495,24.7965,24.7150,24.9339,24.6614,102813980,"Mar 23, 16",-0.1374,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
55,26.4175,26.5625,26.2225,26.3675,AAPL,104531820,HISTORICAL_PRICES,AAPL,,2016-03-24,1606830572000,0.028819,0.028819,105.470,105.67,106.2500,104.8900,26132955,24.5613,24.6079,24.7429,24.4262,104531820,"Mar 24, 16",-0.1071,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
56,26.2975,26.5475,26.2650,26.5000,AAPL,77645488,HISTORICAL_PRICES,AAPL,,2016-03-28,1606830572000,0.024146,0.024146,106.000,105.19,106.1900,105.0600,19411372,24.6847,24.4961,24.7290,24.4658,77645488,"Mar 28, 16",-0.1118,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26.2975,NaN
57,26.9200,26.9475,26.2200,26.2225,AAPL,124760332,HISTORICAL_PRICES,AAPL,,2016-03-29,1606830572000,0.048389,0.048389,104.890,107.68,107.7900,104.8800,31190083,24.4262,25.0759,25.1016,24.4239,124760332,"Mar 29, 16",0.5798,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
58,27.3900,27.6050,27.1500,27.1625,AAPL,182404596,HISTORICAL_PRICES,AAPL,,2016-03-30,1606830572000,0.066693,0.066693,108.650,109.56,110.4200,108.6000,45601149,25.3018,25.5137,25.7140,25.2902,182404596,"Mar 30, 16",0.4378,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
59,27.2475,27.4750,27.2200,27.4300,AAPL,103553796,HISTORICAL_PRICES,AAPL,,2016-03-31,1606830572000,0.061143,0.061143,109.720,108.99,109.9000,108.8800,25888449,25.5510,25.3810,25.5929,25.3554,103553796,"Mar 31, 16",-0.1327,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
60,27.4975,27.5000,27.0500,27.1950,AAPL,103495800,HISTORICAL_PRICES,AAPL,,2016-04-01,1606830572000,0.070879,0.070879,108.780,109.99,110.0000,108.2000,25873950,25.3321,25.6139,25.6162,25.1970,103495800,"Apr 1, 16",0.2329,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
61,27.7800,28.0475,27.5675,27.6050,AAPL,149424816,HISTORICAL_PRICES,AAPL,,2016-04-04,1606830572000,0.081881,0.081881,110.420,111.12,112.1900,110.2700,37356204,25.7140,25.8770,26.1262,25.6791,149424816,"Apr 4, 16",0.2631,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,25.8770
62,27.4525,27.6825,27.3550,27.3775,AAPL,106314608,HISTORICAL_PRICES,AAPL,,2016-04-05,1606830572000,0.069127,0.069127,109.510,109.81,110.7300,109.4200,26578652,25.5021,25.5720,25.7862,25.4811,106314608,"Apr 5, 16",-0.3050,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
63,27.7400,27.7450,27.3000,27.5575,AAPL,105616308,HISTORICAL_PRICES,AAPL,,2016-04-06,1606830572000,0.080323,0.080323,110.230,110.96,110.9800,109.2000,26404077,25.6698,25.8398,25.8444,25.4299,105616308,"Apr 6, 16",0.2678,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
64,27.1350,27.6050,27.0303,27.4875,AAPL,127207480,HISTORICAL_PRICES,AAPL,,2016-04-07,1606830572000,0.056762,0.056762,109.950,108.54,110.4200,108.1210,31801870,25.6046,25.2762,25.7140,25.1786,127207480,"Apr 7, 16",-0.5636,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27.135,NaN
65,27.1650,27.4425,27.0425,27.2275,AAPL,94326960,HISTORICAL_PRICES,AAPL,,2016-04-08,1606830572000,0.057930,0.057930,108.910,108.66,109.7700,108.1700,23581740,25.3624,25.3042,25.5627,25.1901,94326960,"Apr 8, 16",0.0280,...,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
66,27.2550,27.6525,27.2075,27.2425,AAPL,117630072,HISTORICAL_PRICES,AAPL,,2016-04-11,1606830572000,0.061435,0.061435,108.970,109.02,110.6100,108.8300,29407518,25.3764,25.3880,25.7583,25.3437,117630072,"Apr 11, 16",0.0838,...,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
67,27.6100,27.6250,27.1650,27.3350,AAPL,108929300,HISTORICAL_PRICES,AAPL,,2016-04-12,1606830572000,0.075260,0.075260,109.340,110.44,110.5000,108.6600,27232325,25.4625,25.7187,25.7327,25.3042,108929300,"Apr 12, 16",0.3307,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
68,28.0100,28.0850,27.7000,27.7000,AAPL,133029264,HISTORICAL_PRICES,AAPL,,2016-04-13,1606830572000,0.090838,0.090838,110.800,112.04,112.3400,110.8000,33257316,25.8025,26.0913,26.1611,25.8025,133029264,"Apr 13, 16",0.3726,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
69,28.0250,28.0975,27.8325,27.9050,AAPL,101895692,HISTORICAL_PRICES,AAPL,,2016-04-14,1606830572000,0.091422,0.091422,111.620,112.10,112.3900,111.3300,25473923,25.9935,26.1052,26.1728,25.9259,101895692,"Apr 14, 16",0.0139,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,26.1052

In [25]:
?argrelextrema